### ISSUE TITLE
Impossible to read source-rom directory

### ISSUE THREAD

**Issue by Denethor85** [TobiasKoller/RomSetManager#2]
Impossible to read source-rom directory. When click on read button nothing change

**Comment by TobiasKoller** [comment]
I will have a look at this. can you share some information about your folder-structure? maybe a screenshot from your settings and from the directory you try to read from

**Comment by TobiasKoller** [comment]
hi Denethor, 

I'm pretty sure your source-directory has not the structure the tool needs.
Please make sure that your structure looks like this:

![image](https://user-images.githubusercontent.com/15647346/114510719-4a61f480-9c37-11eb-8867-853ed2fdc612.png)

and that the rom-files are in the correct folder.

If you don't have the structure, you can click on "clone directory-structure from retropie" the create the structure from retropie (without roms).

I will update the tool that an useful message will appear to show what the problem is.

Please let me know if it works now.

Best regards
